### ISSUE TITLE
Can't find cmdline.py (twitter 1.10.0)

### ISSUE THREAD

**Issue by slauria** [sixohsix/twitter#162]
After clean install (pip uninstall twitter and then easy_install twitter) I have the 
"ImportError: No module named cmdline".

Previous version of twitter (v1.9.4) was working fine until API V 1 no longer supported.

**Comment by hugovk** [comment]
These three look like duplicates: #67 #162 #281.

**Comment by sixohsix** [comment]
Yep, dupe of #67.
