### ISSUE TITLE
feature: option to just display url for oauth process, not open lynx automatically.

### ISSUE THREAD

**Issue by dragonfax** [sixohsix/twitter#171]
when using -o the tool opens up a lynx browser with the url. Thats pretty jarring, and lynx is pretty hard to use. Its be better just out put out the link, and ask the user to use their own browser manually. Or at least provide an option not to force the user to lynx. It took a while of fiddling to get the app auth browser to work right in lynx on my mac.

**Comment by polm** [comment]
I would really appreciate an option to just show a link. Would it be OK to submit a pull request for this?

**Comment by hugovk** [comment]
@polm Go for it!
