### ISSUE TITLE
App Only Authentication 

### ISSUE THREAD

**Issue by azman0101** [sixohsix/twitter#232]
Hi,

Does it lack something for using app only Authentication with your package ?

Could you provide to me an example of use ?

According to the documentation, the body of the request must have "grant_type=client_credentials" 

I can't find where this parameter is added to the request ...

Thxs

**Comment by robroc** [comment]
@RouxRC Thanks for this workaround. I just want to note that this line:

`tokenclient.oauth2.token(grant_type="client_credentials")`

returns a string of a dict instead of a dict itself. So it needs to be passed into `json.loads()` to work.

**Comment by RouxRC** [comment]
Ha yes indeed, I also do that in personal pieces of code, I'll edit the code, thanks for the feedback!
