### ISSUE TITLE
Update examples to use "media/upload()" instead of the deprecated "update_with_media()"

### ISSUE THREAD

**Issue by jcea** [sixohsix/twitter#279]
Twitter has deprecated "update_with_media()" and now we should use "media/upload()". But the examples documented in this project still use "update_with_media()" and, in fact, I don't know how to use the new API and how to interact with "upload.twitter.com".

I would love to see "media/upload()" examples to integrate pic.twitter.com images in my programmatic tweets :-).

**Comment by RouxRC** [comment]
Hi there! Indeed, the doc is outdated, we should fix that. In the mean time, you can find an example on how to use the new api there in the tests: https://github.com/sixohsix/twitter/blob/master/tests/test_sanity.py#L86-L103
Note the use of the two different twitter instances for upload.twitter and api.twitter here at the top: https://github.com/sixohsix/twitter/blob/master/tests/test_sanity.py#L18-L23

**Comment by jcea** [comment]
Thanks!.

I have a question... When uploading media, does it count against the 140 character limit of twitter?

**Comment by RouxRC** [comment]
Hi @jcea, last time I checked the API limits, you can send up to 4 images/videos in one tweet, accounting for a total length of one https url (so 23 characters these days)
