### ISSUE TITLE
ImportError: No module named cmdline

### ISSUE THREAD

**Issue by hillz1** [sixohsix/twitter#281]
I have successfully installed version 1.16.0 but when I try to run "twitter" from my linux terminal it says like this: http://s17.postimg.org/wim9qyqnz/angel_beats_bg5.jpg

I had no error in version 1.15.0

**Comment by hugovk** [comment]
These three look like duplicates: #67 #162 #281.

**Comment by sixohsix** [comment]
Yep. Dupe of #67,
