### ISSUE TITLE
twitter stream broken pipe

### ISSUE THREAD

**Issue by edi-bice** [sixohsix/twitter#284]
failed due to [Errno 32] Broken pipe

for tweet in tweet_iter:
  File "build/bdist.linux-x86_64/egg/twitter/stream.py", line 176, in __iter__
  File "build/bdist.linux-x86_64/egg/twitter/stream.py", line 133, in read

**Comment by RouxRC** [comment]
This is a typical error when Twitter's servers get slow or have issues, you have to catch these in your code.

**Comment by edi-bice** [comment]
I understand where it comes from and yes I can handle it. Still feel that it is in the spirit of the library to handle these. After all why handle higher level rate-limiting issues but not these?

**Comment by edi-bice** [comment]
"""The iterator will yield until the TCP connection breaks. When the
    connection breaks, the iterator yields `{'hangup': True}`, and
    raises `StopIteration` if iterated again."""

And here's how I test for that - though it doesn't seem to come through as Hangup

    for tweet in tweet_iter:
...
        elif tweet is HeartbeatTimeout:
            printNicely("-- Heartbeat Timeout --")
            raise BrokenTwitteratorException("Heartbeat timeout")
...
        elif tweet is Hangup:

**Comment by RouxRC** [comment]
Indeed, it would make more sense.
@sixohsix how would you feel:
- either removing the raise here https://github.com/sixohsix/twitter/blob/master/twitter/stream.py#L139 and replace it with a raise dedicated TwitterHttpError
- either keep the raise but surround the sock_reader.read() line 176 with a try/catch such as:
<pre>
try:
    data = sock_reader.read()      
catch SSLError:
    yield Hangup
    break
</pre>

**Comment by RouxRC** [comment]
it's been a while, I'm taking the initiative of the second option, @sixohsix please do if you prefer another solution

**Comment by sixohsix** [comment]
Oops... sorry for totally missing this for so long. Yes, I totally agree with your decision. Thank you for fixing this.

**Comment by RouxRC** [comment]
I took the liberty of closing some dying issues without answers from their authors.
A bunch of the left ones regard the CLI and bot which i've never used and don't feel comfortable taking a look at.
Hapy new year!
