### ISSUE TITLE
How can I send a tweet including a hyper link?

### ISSUE THREAD

**Issue by erogol** [sixohsix/twitter#289]

**Comment by hugovk** [comment]
Just put it in the status text:

```python
t.statuses.update(
    status="How can I send a tweet including a hyper link? https://github.com/sixohsix/twitter/issues/289")
```

The link will counted as something like 21 characters for HTTP and something like 22 characters for HTTPS.

Have you tried that? What happened?

**Comment by RouxRC** [comment]
Looks closable, @erogol please reopen if necessary
