### ISSUE TITLE
How to get headers and messages for public stream API?

### ISSUE THREAD

**Issue by diegoaguilar** [sixohsix/twitter#290]
According to [docs](https://dev.twitter.com/streaming/overview/messages-types#limit_notices) and this official post in [forums](https://twittercommunity.com/t/1-of-the-firehose-via-streaming-api-even-when-only-searching-very-specific-keywords/9712/2), sometimes a connection could be delivering less tweets that existing ones. I wonder how can I get this sort of messages using `twitter`.

My current implementation is as simple as this:

```
query_term = sys.argv[1]
twitter_stream = TwitterStream(auth=auth)

iterator = twitter_stream.statuses.filter(track=query_term,language='es')

for tweet in iterator:
    print tweet['text']
```

I assume that for any term, at any time something like this could be received:

```
{
  "limit":{
    "track":1234
  }
}
```

So I need to get noticed if at any time I'm missing some tweets. How could I achieve it?

**Comment by RouxRC** [comment]
Just test whether text is actually present in tweet before trying to print it, otherwise test whether limit.track is in it, something like:
```python
for tweet in iterator:
    try:
        print tweet['text']
    except KeyError:
        if 'limit' in tweet:
            print >> sys.stderr, "WARNING : stream overcharged, missed %d tweets since the beginning" % tweet['limit']['track'] 
```

**Comment by diegoaguilar** [comment]
But couldn't it be an scenario where I'm actually getting tweets but they're telling me that they're just not sending whole tweets on that tracked term available?

Due to the docs I refer I understand it could. And in the example you provide, it's like somehow there's not actual tweets ...

**Comment by RouxRC** [comment]
it means the stream most of the times send tweets (dict with a text field included) and sometimes when it has to sends other kind of messages, also a dict but with a different shape, like for instance those to tell you that there are too many tweets compared to what you can get
Just try!

**Comment by diegoaguilar** [comment]
Thanks, I love and have used tpt many times but I get confused with docs oftently. What's best way to contact and ask for any doubt?

Thanks again for your great job!

**Comment by RouxRC** [comment]
Thanks, although we really are mainly discussing the source behaviour of Twitter's streaming api here :)

**Comment by diegoaguilar** [comment]
Alright, it's just I have some other distinct doubs and wonder if I should open a new issue for each or keep on here :)
