### ISSUE TITLE
How should I do processing over stream API responses using python twitter tools?

### ISSUE THREAD

**Issue by diegoaguilar** [sixohsix/twitter#291]
[Reading docs I found](https://dev.twitter.com/streaming/overview/processing):

> ### Falling behind
Clients which are unable to process messages fast enough will be disconnected. A way to track whether your client is falling behind is to compare the timestamp of the Tweets you receive with the current time. If the difference between the timestamps increases over time, then the client is not processing Tweets as fast as they are being delivered. Another way to receive notifications that a client is falling behind is to pass the stall_warnings parameter when establishing the streaming connection.

So I wonder:

How should I enable such `stall_warnings`?

Would ` twitter_stream.statuses.filter(track=query_term,language='es', stall_warnings=True)` be appropiate?

Then, just to confirm, in this case below should I use/implement any message or queue system?

```
iterator = twitter_stream.statuses.filter(track=query_term,language='es')

for tweet in iterator:
    try:
        print tweet['text']
        # Further processing, disk saving, db saving, etc using something like zmq or rabbitmq here
```

**Comment by sixohsix** [comment]
`stall_warnings=True` should work. Try it and let me know if it doesn't.

You could use an mq or database to offload processing, but you might want to try it without it and implement it later as an optimization if you encounter stall issues. It depends entirely on your use case.
