### ISSUE TITLE
Problem with authentication

### ISSUE THREAD

**Issue by julianosilvaa** [sixohsix/twitter#295]
Dear!

Please may you help me to set the variables of the twitter authentication?

I got this error:
raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 401 for URL
....
details: {u'errors': [{u'message': u'Could not authenticate you.', u'code': 32}]}

And that is my python file:
con_secret_key: Consumer Secret (API Secret) from Application's page from Twitter Dev.
con_secret: Consumer Key (API Key) from Application's page from Twitter Dev.
token: Access Token from Application's page from Twitter Dev.
token_key: Access Token Secret from Application's page from Twitter Dev.

t = Twitter(
  auth=OAuth(token, token_key, con_secret, con_secret_key))

Appreciate any help if possible.

Thanks in advance.

Regards.
Juliano.

**Comment by RouxRC** [comment]
Hi, the names are always a bit confusing, you should have something like this:
Oauth('xxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'xxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

**Comment by julianosilvaa** [comment]
Thank you Benjamin!
You know I'm new in development and simples things can take time to solve, but I'll study hard ;)
