### ISSUE TITLE
Timing out on direct message stream

### ISSUE THREAD

**Issue by Debreo** [sixohsix/twitter#296]
Hey guys,

I created a twitterbot thats sole purpose is to stream direct messages and reply back to them. I wanted to have it constantly streaming, and I was wondering if there was a way to override hangups. I currently have the twitterstream set to (block=True, timeout=None, heartbeat_timeout=None). It's still hanging up and closing on the next iteration if it doesn't receive any messages after a while. 

A solution I created was I created a bash nohup script that re executes the script everytime it goes down. This works for a while, but starts giving me errors such as 
twitter.api.TwitterHTTPError: Twitter sent status 503 for URL: 1.1/user.json using parameters.

So is there a way to constantly stream direct messages without it quitting out after inactivity.

**Comment by RouxRC** [comment]
The default settings should do what you want, although sometimes you get disconnected by Twitter and there's nothing you can do about that except handle it from your code directly, for instance as such:

```python
while True:
    try:
        for t in twitterstream.statuses.filter(track=",".join(keywords), filter_level='none', stall_warnings='true'):
            # do stuff with your messages
    except (TwitterHTTPError, BadStatusLine, URLError, SSLError, socket.error) as e:
        log("WARNING", "Stream connection lost, reconnecting in a sec... (%s: %s)" % (type(e), e))
        time.sleep(2)
        continue
```

**Comment by Debreo** [comment]
@RouxRC Thank you for your response. I've added a while condition to my script and had a try and except for the userstream function. I'm hoping this will do what I need. 

Thanks again!

**Comment by RouxRC** [comment]
Looks closable now, @Debreo please reopen if necessary
