### ISSUE TITLE
How can I use a proxy ?

### ISSUE THREAD

**Issue by Yutsa** [sixohsix/twitter#297]
Hello, I need to be able to use a Proxy. How could I do so that the resquests done by your API goes through a proxy ?

**Comment by RouxRC** [comment]
Hi, I don't believe proxy were ever considered in this project, I'm afraid you will need:
- either to set it globally in your system (at least linux machines can let you do that)
- or have a look at the code and try to propose a pull request to add such an option to the Twitter (here: https://github.com/sixohsix/twitter/blob/master/twitter/api.py#L310-L523 ) and TwitterStream classes (there: https://github.com/sixohsix/twitter/blob/master/twitter/stream.py#L205-L289 )

**Comment by Yutsa** [comment]
It's ok I modified the code to use a proxy. It was not as hard as I thought it would be.

**Comment by RouxRC** [comment]
It could be useful to include it as an option of this library for other users, could you maybe share your modifications so we can see how to include it properly?

**Comment by Yutsa** [comment]
I'm not sure if it's working properly. I put : 

proxy_support = ProxyHandler({"http":"http://176.31.170.48:3128"})
        opener = build_opener(proxy_support)
        install_opener(opener)

in the TwitterCall __init__

I check the ip just before the resquest was sent and it's the proxy address. So I hope it's working.

**Comment by RouxRC** [comment]
Thanks.
PS: you might not want to give out publicly the IP of your proxy ;)

**Comment by Yutsa** [comment]
Oh it's from proxy list so it's already a public Proxy.

**Comment by Yutsa** [comment]
Oh so apparently it's not working.
I do a request to get my ip just before the request sent to twitter and it displays the proxy address but even if I use a wrong proxy address the request to twitter works.

So I guess the API doesn't use the proxy for its request and I really don't know why...

I put 

```python
proxy_support = ProxyHandler({"http":"176.31.170.48:3128"})
opener = build_opener(proxy_support)
install_opener(opener)
```
 in the __init__ of the TwitterCall class.

```python
# Request
        try:
            # Request to a website that returns your ip
            req = urllib_request.Request('http://ip.42.pl/raw')
            test = urlopen(req)
            print('my ip is : ' + str(test.read()))
        except Exception as e:
            print(e)
        req = urllib_request.Request(url_base, data=body, headers=headers)
```

The request to get my ip returns the proxy address so I thought it was working.
Although, as I said, I ran the script with a wrong IP address, I got an error for the request that tried to get my ip, which is normal but after that the script still sent tweets.

Any idea why didn't the twitter request go through the proxy ? 
I mean the request is sent the same way in both cases so why is it going through the proxy for one request and not for the other ?

**Comment by RouxRC** [comment]
@yutsa still some problems or not?

**Comment by Yutsa** [comment]
I made a mistake the first time. I used the proxy for http but the twitter requests are in https. So I edited my previous post. It works perfectly fine now.

**Comment by RouxRC** [comment]
Nice, thx!
