### ISSUE TITLE
Handle non JSON error respones

### ISSUE THREAD

**Issue by plouj** [sixohsix/twitter#298]
I've noticed that sometimes twitter returns html instead of json that looks like:
```
</head>
<body>
<h2>HTTP ERROR: 401</h2>
<p>Problem accessing '/1.1/user.json'. Reason:
<pre>      Unauthorized</pre>
</body>
</html>
```
Which causes a ```ValueError: No JSON object could be decoded``` exception in https://github.com/sixohsix/twitter/blob/master/twitter/stream.py#L209.

I found that simply passing an empty string ```''``` instead of ```'json'``` to ```TwitterHTTPError``` on that line to be an effective solution.

**Comment by RouxRC** [comment]
Looks to me like a residual effect of #287, what do you think @jessamynsmith ?
Maybe just add a try around the json.loads call in https://github.com/sixohsix/twitter/pull/287/files#diff-ca47863eef03007ed84692b07b74eda6 ?
@sixohsix an opinion?

**Comment by jessamynsmith** [comment]
Hm, I don't think a simple try/except is quite right -- it needs a little refactoring first. I'll pull something together.
