### ISSUE TITLE
Incorrect URL for statuses.retweeters.ids endpoint

### ISSUE THREAD

**Issue by dellsystem** [sixohsix/twitter#300]
When trying to make use of the [statuses/retweeters/ids](https://dev.twitter.com/rest/reference/get/statuses/retweeters/ids) endpoint, I get:

```python
>>> t.statuses.retweeters.ids(id='1234')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dellsystem/env/local/lib/python2.7/site-packages/twitter/api.py", line 308, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/home/dellsystem/env/local/lib/python2.7/site-packages/twitter/api.py", line 341, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 404 for URL: 1.1/statuses/retweeters/ids/1234.json using parameters: ()
details: {u'errors': [{u'message': u'Sorry, that page does not exist', u'code': 34}]}
```

The problem is that the statuses.retweeters.ids(id=1234) is being transformed into the url "1.1/statuses/retweeters/ids/1234.json", when it should really be "1.1/statuses/retweeters/ids.json" with id=1234 as a parameter.

One way to fix this is by handling this specific endpoint as an edge case in lines 168-174 of twitter/api.py, changing the code from

```python
    # If an id kwarg is present and there is no id to fill in in
    # the list of uriparts, assume the id goes at the end.
    id = kwargs.pop('id', None)
    if id:
        uri += "/%s" % (id)

    return uri
```

to

```python
    # If an id kwarg is present and there is no id to fill in in the list of
    # uriparts, assume the id goes at the end (unless it's the retweeters
    # endpoint).
    if 'statuses/retweeters/ids' not in uri:
        id = kwargs.pop('id', None)
        if id:
            uri += "/%s" % (id)

    return uri
```

That gets rid of the error, but it's pretty ugly hack, so I thought I would just open an issue and see if anyone can find a better workaround.

**Comment by miv-ableton** [comment]
Hi,

The immediate workaround for that endpoint is to do this:

```python
t.statuses.retweeters.ids(_id='1234')
```

(Note the underscore in the parameter).

I'm loath to account for this edge case in the code, as the Twitter API is extremely inconsistent and variable, and I don't want to chase down all the edge cases directly in the code. However, I already do something like this for GET vs POST. Maybe I can combine your change with that approach. Thanks for the suggestion!

**Comment by dellsystem** [comment]
Makes sense. Thanks Mike!

**Comment by RouxRC** [comment]
just discovered there is the same problem for the favorites.create, so adding this one as documentation as well :)
