### ISSUE TITLE
Error on every request

### ISSUE THREAD

**Issue by Mids123** [sixohsix/twitter#301]
I've tryied to perform the examples on the README.md, and I've got the same error on every request that I did.

Here is an example:

>>> t.statuses.home_timeline()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-armv6l/egg/twitter/api.py", line 263, in __call__
AttributeError: 'tuple' object has no attribute 'generate_headers'

And another: 

>>> t.statuses.update(status="Test")
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "build/bdist.linux-armv6l/egg/twitter/api.py", line 263, in __call__
AttributeError: 'tuple' object has no attribute 'generate_headers'

**Comment by dellsystem** [comment]
I suspect it's because you're initialising it like this:

```
t = Twitter(auth=(token, token_key, con_secret, con_secret_key))
```

where the auth kwarg is a tuple instead of an OAuth instance as it shows in the readme. According to the readme, It should be like this:

```
t = Twitter(auth=OAuth(token, token_key, con_secret, con_secret_key))
```

Hope that helps

**Comment by Mids123** [comment]
Thank you!, I had that wrong. 
Problem solved
