### ISSUE TITLE
Auth process unsecure ?

### ISSUE THREAD

**Issue by JPFrancoia** [sixohsix/twitter#303]
Hi,

I want to make a GUI application which will allow the user to tweet some data. So the first time the user will use this feature, he will have to authenticate. But I don't understand the process. In the doc, there is this piece of code:

``` python
from twitter import *

MY_TWITTER_CREDS = os.path.expanduser('~/.my_app_credentials')
if not os.path.exists(MY_TWITTER_CREDS):
    oauth_dance("My App Name", CONSUMER_KEY, CONSUMER_SECRET,
                MY_TWITTER_CREDS)

oauth_token, oauth_secret = read_token_file(MY_TWITTER_CREDS)

twitter = Twitter(auth=OAuth(
    oauth_token, oauth_token_secret, CONSUMER_KEY, CONSUMER_SECRET))

# Now work with Twitter
twitter.statuses.update(status='Hello, world!')
```

I'm not really sure I understand what I need to do. Do I have to put my consumer key, and my consumer secret, in a file readable by the user ? Isn't it deprecated ?

Sincerely

**Comment by gyazbek** [comment]
Are you trying to make a web service tool that allows you to post on behalf of other users? If so they will need to authorize your Twitter application first, at which point you'll be given a token that you will use to tweet on their behalf (think hootsuite). 

Or did intend for your users to put their credentials on your application? (you shouldn't do this, as a user should have the ability to revoke access to your application at anytime, hence the pre-authorized oauth token)

Take a look at the api doc overview for oauth https://dev.twitter.com/oauth/overview
