### ISSUE TITLE
Twitter REST API 1.1 Support

### ISSUE THREAD

**Issue by snehi23** [sixohsix/twitter#304]
I am trying "twitter" package to call new search api (1.1) but got following error.

twitter.api.TwitterHTTPError: Twitter sent status 404 for URL: 1.1/search/tweets.json using parameters:

I searched through the problems and got this link which simulate my query
http://stackoverflow.com/questions/5521848/problem-with-twitter-package-by-sixohsix

The answer specifically mentioned that this problem is solved in newer version of "twitter" but i getting same problems.

I am using : latest version of "twitter" : 1.17.1

**Comment by RouxRC** [comment]
Hi, the stackoverflow link you're giving is 4 years old, it will hardly reflect your current situation.
Can you paste more info like the actual code you're writing that returns this error?

**Comment by snehi23** [comment]
I am trying this code:
-------------------------------------------------------------------------------------------------------------------------------------------
try:
    import json
except ImportError:
    import simplejson as json

from twitter import Twitter, OAuth, TwitterHTTPError, TwitterStream

from pymongo import MongoClient

ACCESS_TOKEN = ‘####'
ACCESS_SECRET = ‘####'
CONSUMER_KEY = ‘####'
CONSUMER_SECRET = ‘####'

oauth = OAuth(ACCESS_TOKEN, ACCESS_SECRET, CONSUMER_KEY, CONSUMER_SECRET)

twitter_stream = TwitterStream(auth=oauth)

iterator = twitter_stream.search.tweets(q='#India')

tweet_count = 1000
for tweet in iterator:
    tweet_count -= 1
    client = MongoClient('localhost',27017)
    db = client['twitter_db']
    collection = db['twitter_collection']
    collection.insert(tweet)
    if tweet_count <= 0:
        break
-------------------------------------------------------------------------------------------------------------------------------------------
Output : 
twitter.api.TwitterHTTPError: Twitter sent status 404 for URL: 1.1/search/tweets.json using parameters:
details: Unknown URL. See Twitter Streaming API documentation at http://dev.twitter.com/pages/streaming_api

**Comment by snehi23** [comment]
This issue is not solved. Please have a look on the code I posted.

**Comment by RouxRC** [comment]
Well you're calling the REST Search API via the Streaming API, so it cannot work.

If you want to query the stream you should use:
```python
twitter_stream = TwitterStream(auth=oauth)
iterator = twitter_stream.filter(track='#India')
```

Or if you want to use the search:
```python
twitter_rest_api = Twitter(auth=oauth)
iterator = twitter_rest_api.search.tweets(q='#India')
```

The api documentation linked in your output says it all.

**Comment by snehi23** [comment]
Hi RouxRC, 

Thanks you for clarification.

As you suggested, I tried search with

twitter_rest_api = Twitter(auth=oauth)
iterator = twitter_rest_api.search.tweets(q='#India')

and its working fine but stream API with 

twitter_stream = TwitterStream(auth=oauth)
iterator = twitter_stream.filter(track='#India')

still gives me error :

"twitter.api.TwitterHTTPError: Twitter sent status 404 for URL: 1.1/filter.json using parameters:"

Sorry for late reply.

**Comment by RouxRC** [comment]
my mistake, as the doc says, the proper stream route is statuses.filter, so:
```
 iterator = twitter_stream.statuses.filter(track='#India')
```

**Comment by snehi23** [comment]
Thanks. Its working now.
