### ISSUE TITLE
Coverage makes travis fail with python 3.2

### ISSUE THREAD

**Issue by RouxRC** [sixohsix/twitter#310]
Just pushed a fix for the tests to still work now that all t.co links from twitter are given as https.
It solves the Travis fail we had earlier today, but although there is no issue on the lib side, Travis is causing a problem.
The tests should still pass, but it seems like coverage support for python 3.2 does not function anymore: https://travis-ci.org/sixohsix/twitter/jobs/92786383
Not sure what to do here, seems too bad to drop python 3.2 support just because of this, maybe just change the Travis config? @sixohsix what do you think?

**Comment by hugovk** [comment]
I know how to fix this, just use the old version of Coverage for Python 3.2.

I'll submit a PR.

**Comment by hugovk** [comment]
PR #311 submitted.

**Comment by RouxRC** [comment]
Great thanks!
I'll merge as soon as travis finishes :)

**Comment by RouxRC** [comment]
shooting too fast, we're having twitter api rate limits issues now :p will have to wait for a bit

**Comment by hugovk** [comment]
Sure.

Passed on my repo:
https://travis-ci.org/hugovk/twitter/builds/92791268
https://travis-ci.org/hugovk/twitter/builds/92790499

**Comment by RouxRC** [comment]
Will merge in 30 so we're sure to be ok with api limits
