### ISSUE TITLE
How to retrieve someone's all tweets except replies and retweets

### ISSUE THREAD

**Issue by S1U** [sixohsix/twitter#314]
tried this `t.statuses.user_timeline(screen_name="name")`, but looks not get all tweets, and also included replies and retweets.

How to get all and exclude replies and retweets?

**Comment by RouxRC** [comment]
Please look at Twitter's API documentation for any detail on the arguments for each route
https://dev.twitter.com/overview/documentation

For instance for user_timeline https://dev.twitter.com/rest/reference/get/statuses/user_timeline

**Comment by RouxRC** [comment]
closable?
