### ISSUE TITLE
How to install twitter package?

### ISSUE THREAD

**Issue by thinhduckhoi** [sixohsix/twitter#320]
Could someone tell me how to install twitter package please?

**Comment by RouxRC** [comment]
As for any PyPI package, by using `pip`:

```bash
pip install twitter
```

**Comment by RouxRC** [comment]
closable?

**Comment by sixohsix** [comment]
@RouxRC looks closeable to me. I'd recommend just closing these if there's no reply after a week or so. It's easy to reopen an issue if the reporter really wants to. Thanks for keeping a handle on these!

**Comment by RouxRC** [comment]
all right, I closed a couple following this rule then.
Also, I tagged `CLI` and `ircbot` issues related to these two parts of the lib which I never used and don't feel comfortable maintaining, so i'll let you deal with these ;)
