### ISSUE TITLE
Parsing t.search.tweets response

### ISSUE THREAD

**Issue by vmesel** [sixohsix/twitter#325]
Hello, I'm currently running a script that I need to parse the response of the  t.search.tweets.

The code is
```
t = Twitter(auth=OAuth(settings.token, settings.tokensecret, settings.consumerkey, settings.consumersecret))
s = t.search.tweets(q="#guerracivil")
```
How it can be made? I already tried parsing with json.load and with an intermediate file, but they all return with error!

**Comment by vmesel** [comment]
This can be parsed as a normal string, you just need:

```
for status in statuses:
    print(status['source'])
```

**Comment by boogheta** [comment]
Yeah this lib already pickles every json results from Twitter's API as python dictionaries, so you can work with it just as with regular objects

**Comment by vmesel** [comment]
Thanks @boogheta
