### ISSUE TITLE
Media metadata: alt text support

### ISSUE THREAD

**Issue by hugovk** [sixohsix/twitter#326]
Twitter has added a media metadata API endpoint. Currently it supports adding alt text to an image: https://blog.twitter.com/2016/alt-text-support-for-twitter-cards-and-the-rest-api

Other parts of the API are also being extended with a `include_ext_alt_text` parameter.

The above link notes that "Full documentation for this endpoint will soon be published and linked directly once available".

---

(Issue copied from [tweepy](https://github.com/tweepy/tweepy/issues/716), they have a [PR](https://github.com/tweepy/tweepy/pull/727) too.)

**Comment by RouxRC** [comment]
the official doc is here https://dev.twitter.com/rest/reference/post/media/metadata/create
it should work with the above commit calling :
```
twitter_upload_conn.media.metadata.create(POST_json={"media_id": ID, "alt_text":{"text": "It works!"}})
```
still need to add testing and documentation
I feel like it's more the philosophy of this lib to give a standard way of calling such kind of routes that send json data with POST instead of the usual routes, but we could add shortcuts to this specific route that would just take media_id and alt_text maybe, not sure, @sixohsix what do you think?

**Comment by hugovk** [comment]
Thank you!

I agree a more user-friendly wrapper would be good, either instead or as well (for more flexibility in the future). 

Like in the Tweepy PR.

**Comment by sixohsix** [comment]
I think this is a nice workaround, and I'm glad you got it ready so quickly.

I would prefer if you separate the need for json data from the need for the POST method. We already have a `_method` parameter. So to keep the two exclusive I would suggest that the function be called like:

```
twitter_upload_conn.media.metadata.create(
    _method="POST",
    _json={"media_id": ID, "alt_text":{"text": "It works!"}})
```

I suppose json with GET might be weird but Twitter is weird and who knows, they might do it. As well, _explicit is better than implicit_ and explicitly setting the `_method` feels right to me.

You should also add "metadata/create" to the list of POST actions in `twitter_globals.py`. Then the call should default to POST and you can do:

```
twitter_upload_conn.media.metadata.create(
    _json={"media_id": ID, "alt_text":{"text": "It works!"}})
```

Of course this is no longer explicit, but it's convenient, and we have lots of precedent for this.

What do you think?

**Comment by RouxRC** [comment]
All right, done this and added python3 handling, doc and tests.
I'm adding via a PR handling shortcut arguments for this function as suggested by @hugovk , it might not be the direction you want the lib to take @sixohsix so i'll let you decide. If we go for it and other cases appear, we could think to some kind of formalization of the thing in some kind of "helper modules"

**Comment by kerstin** [comment]
@RouxRC Looks like this issue is more appropriate for my question (no idea why I've missed this one so far). So, is your linked PR the actual code for adding alt text? (... which goes with the test and info regarding adding alt text, which already exist somewhere in this repo?)

**Comment by RouxRC** [comment]
Hi @kerstin. The PR only proposes an easier way to do it, but you should already be able to do it with the master branch, as documented here https://github.com/sixohsix/twitter/blob/master/README#L124-L150
Probably not with the latest release though, you'll have to install from git such as `pip install git+https://github.com/sixohsix/twitter`.

**Comment by kerstin** [comment]
@RouxRC Ahhh, ok, that's it then! Duh/grah. I only ever worked with the pip-installed version and was confused about why I found references to it in the code on here but couldn't get it to work... Will try again with this version tomorrow. (A hint about that in the README might help? Even if it's as little as reminding people/making them aware the release might be a little behind this repo.)

**Comment by RouxRC** [comment]
Or simply publish a release when required, cf #356 ;)

**Comment by kerstin** [comment]
Yeah, just realised now that updating the library from here works fine for when I run my project locally, but won't work for the cloud-hosted version...!
