### ISSUE TITLE
twitter-archiver doesn't need "Write and Access direct messages"

### ISSUE THREAD

**Issue by hugovk** [sixohsix/twitter#327]
Hi @StalkR,

Thanks for twitter-archiver!

Looks like twitter-archiver isn't working without the `--oauth` option:
```python
$ twitter-archiver nasa
* Archiving nasa tweets in ./nasa
Fail: Twitter sent status 400 for URL: 1.1/statuses/user_timeline.json using parameters: (count=200&screen_name=nasa&include_rts=1)
details: {u'errors': [{u'message': u'Bad Authentication data.', u'code': 215}]}
Retrying...
Fail: Twitter sent status 400 for URL: 1.1/statuses/user_timeline.json using parameters: (count=200&screen_name=nasa&include_rts=1)
details: {u'errors': [{u'message': u'Bad Authentication data.', u'code': 215}]}
Retrying...
^C
Interrupted
```

Anyway, when I run it with `--oauth` it asks for more permissions than needed:

> This application will be able to:
 * Read Tweets from your timeline.
 * See who you follow, and follow new people.
 * Update your profile.
 * Post Tweets for you.
 * Access your direct messages.

![image](https://cloud.githubusercontent.com/assets/1324225/15189689/b8be7226-17b4-11e6-8239-0a319bd684f6.png)

Now Twitter has more fine-grained permissions than when the tool was originally written, these should be refined.

If you go to https://apps.twitter.com/ and then the permissions tab for T-Archiver, you'll see the options:

 * Read only
 * Read and Write
 * Read, Write and Access direct messages

I guess it's got the last one, but please could you change it to the first one?

Thank you!

**Comment by StalkR** [comment]
Hey, thanks for the heads-up, done!

> This application will be able to:
> Read Tweets from your timeline.
> See who you follow.

And sorry to hear it doesn't work anymore without oauth. I stopped using/maintaining it a few years ago, but feel free to take a stab at it if you'd like.

**Comment by hugovk** [comment]
Thanks for updating it, that's good enough for me :)
