### ISSUE TITLE
Unclickable /twitter directory on GitHub

### ISSUE THREAD

**Issue by hugovk** [sixohsix/twitter#331]
On the repo's homepage https://github.com/sixohsix/twitter, the `twitter` directory appears blank and is unclickable:

![image](https://cloud.githubusercontent.com/assets/1324225/15421990/b798c470-1e7e-11e6-97ab-4bba71196e7f.png)

But the directory exists: https://github.com/sixohsix/twitter/tree/master/twitter

Any idea what's up?

**Comment by dellsystem** [comment]
Could it be an issue with your browser? Renders fine for me:

![image](https://cloud.githubusercontent.com/assets/628981/15429801/8a49ea52-1e70-11e6-863e-83fed9d54429.png)

**Comment by hugovk** [comment]
Whoops, it was caused by AdBlock! Thanks and sorry for the false alarm!
