### ISSUE TITLE
Archive all tweets (>3200)

### ISSUE THREAD

**Issue by agrawalamod** [sixohsix/twitter#341]
twitter-archiver stops are archiving 3200 tweets. There is a limitation of 3200 tweets. Any way to bypass this limit?  

(I want to dump the complete timeline of a user.)

**Comment by RouxRC** [comment]
nope, this is a twitter api limititation, see here https://dev.twitter.com/rest/reference/get/statuses/user_timeline

**Comment by RouxRC** [comment]
if you own the user's account, you can get all the tweets from the settings in the web interface

**Comment by agrawalamod** [comment]
Thanks.
