### ISSUE TITLE
upload multiple images : error media type unrecognized

### ISSUE THREAD

**Issue by gg4u** [sixohsix/twitter#343]
Hello, I would like to upload a set of images, but from the web, not from my server.

So, I am trying to upload as base64.

How do I configure type of media?
Example:

```
params = {"media[]": base64_image, "status": "PTT ★", "_base64": True}
t.statuses.update_with_media(**params)
```

Like this it works fine, but if if I add a list of images, it seems it just picks first one in the tweet:

```
params = {"media[]": [ base64_image_1, base64_image_2, base64_image_3], "status": "PTT ★", "_base64": True}
t.statuses.update_with_media(**params)
```

Instead, if I try:

```
id_img1 = t_upload.media.upload(media=imagedata_1)["media_id_string"]
id_img2 = t_upload.media.upload(media=imagedata_2)["media_id_string"]
# - finally send your tweet with the list of media ids:
t.statuses.update(status="PTT ★", media_ids=",".join([id_img1, id_img2]))
```

with imagedata_1 and imagedata_2 as base64,

I will have an error:
`details: {u'request': u'/1.1/media/upload.json', u'error': u'media type unrecognized.'}`

I tried with:
`t.statuses.update(status="PTT ★", media_ids=",".join([base64_image, base64_image_2]), _base64="True")`
but:

`details: {u'errors': [{u'message': u'media_ids parameter is invalid.', u'code': 44}]}`

Which parameter should I add to 
`t.statuses.update(status="PTT ★", media_ids=",".join([id_img1, id_img2]))`

to handle a list of base64 images?

And how to insert a list with:

```
params = {"media[]": base64_image_list, "status": "PTT ★", "_base64": True}
t.statuses.update_with_media(**params)
```

Thank you.

**Comment by RouxRC** [comment]
Hi,

statuses/update_with_media is deprecated and can only send one image per tweet https://dev.twitter.com/rest/reference/post/statuses/update_with_media

So the second solution should be the good one but using the _base64 argument when calling media/upload:

```python
id_img1 = t_upload.media.upload(media=image_base64_1, "_base64": True)["media_id_string"]
id_img2 = t_upload.media.upload(media=image_base64_2, "_base64": True)["media_id_string"]
# - finally send your tweet with the list of media ids:
t.statuses.update(status="PTT ★", media_ids=",".join([id_img1, id_img2]))"
```

**Comment by du5** [comment]
HI @RouxRC !

Everything works fine when i upload the picture, it's broke while uploading the video.Where am I doing wrong?

```python3
if (os.path.splitext(url)[-1][1:]).lower() not in ["jpg", "jpeg", "gif", "png", "webp", "mp4", "mov"]:
    return
response = requests.get(file.file_path)
old_domain = twitter.domain
twitter.domain = 'upload.twitter.com'
id_img1 = twitter.media.upload(media=response.content)["media_id_string"]
twitter.domain = old_domain
twitter.statuses.update(status=text, media_ids=",".join([id_img1]))
```
