### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by davidswelt** [sixohsix/twitter#345]
There is no obvious link to some documentation of the Python API on the website.  I'm getting the commandline tool, and that works and prints help.  I can do help("twitter") in python, and that works, thankfully, but a website with the documentation would be good to have.

**Comment by RouxRC** [comment]
Hi, for the python library, most useful info is in the README there https://github.com/sixohsix/twitter

What are you looking for? There is no list of every twitter API function as this library does not rename everything, you only need to apply routes and arguments of the official twitter api documented here https://dev.twitter.com/rest/public
for instance to call "statuses/show/:id" you call `twitter.statuses.show(id=A_TWEET_ID)`
