### ISSUE TITLE
The Twitter REST API v1 is no longer active. Please migrate to API v1.1

### ISSUE THREAD

**Issue by zufanka** [sixohsix/twitter#349]
`$ twitter search \#klimaat`
`Twitter sent status 410 for URL: search.json using parameters: (oauth_consumer_key=xxxxxxxxxxxxxxxx&oauth_nonce=xxxxxxxxxxxxxxxx&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1482147150&oauth_token=xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx&oauth_version=1.0&q=%2523klimaat&oauth_signature=xxxxxxxxxxxxxxxx)
details: {'errors': [{'message': 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.', 'code': 64}]}
Use 'twitter -h' for help.`

is there something I can do?

Python 3.5.2 :: Anaconda 4.2.0 (64-bit)

**Comment by boogheta** [comment]
Hi,

The CLI commands are not at all up to date, hence the messages. You can propose a pull request to fix this :)
It basically lies in adapting this piece of code http://blog.alphoenix.net/2016/12/combien-de-fois-jean-christophe-cambadelis-a-t-il-siege-en-commission-des-affaires-etrangeres/ to the current search api described there https://dev.twitter.com/rest/reference/get/search/tweets

**Comment by zufanka** [comment]
Hi!

Thanks ..  I unfortunately can't do *that*.
Shame, seems very useful :)

**Comment by SocietalTrends** [comment]
Hi Ms.zufanka.
I suggest just for your information,
How about you try git-clone this repository now?
So you execute setup.py in it and install the twitter.
Now, your codes must be executed successfully.

**Comment by kerstin** [comment]
@boogheta I'm getting the same error when trying to post alt text along with images... is that related to this issue or am I doing something wrong on my end? Thanks.

**Comment by smsaladi** [comment]
Facing this issue as well

**Comment by RouxRC** [comment]
@kerstin Do you do so as explained at the bottom of the readme using the `_json` argument ? Support for alt text along images was added with #326 and should normally work using it.

**Comment by kerstin** [comment]
@RouxRC I don't know rn since it's been a while since I used the library to do this. Also, we talked in the issue you linked – I said I could get it to work with a local version, but not with a cloud-hosted one that relies on the last version found on PyPI. (Not sure if you meant to say it should always work now or...?)
