### ISSUE TITLE
NameError: name 'Twitter' is not defined

### ISSUE THREAD

**Issue by pikkupr** [sixohsix/twitter#350]
I'm using Python3.5 on ubuntu 16

```
from twitter import *

t = Twitter(auth=OAuth(access_token, access_secret, 
	consumer_key, consumer_secret))
print(t)
```
when i run the code I get the error "NameError: name 'Twitter' is not defined"

**Comment by RouxRC** [comment]
How did you install the library?

**Comment by hugovk** [comment]
Also, do you have a subdirectory called twitter? That could cause problems.

**Comment by pikkupr** [comment]
@RouxRC 
I've installed library using pip command - sudo pip install git+https://github.com/sixohsix/twitter.git

**Comment by pikkupr** [comment]
@hugovk 
can you explain "Also, do you have a subdirectory called twitter? That could cause problems."
Thanks for the help!

**Comment by hugovk** [comment]
From the place you run your script, do "ls". Is there a folder called "twitter"?

**Comment by pikkupr** [comment]
Yea! there was a folder named twitter there. But now I've removed it and I'm still getting the same error message!

**Comment by RouxRC** [comment]
can you give the results of `pip list` and/or `sudo pip list` ?

**Comment by RouxRC** [comment]
Also, I'm not quite familiar with python3.5, maybe there's a dedicated pip command?
What's the output of `python --version` ? If it isn't python3.5, you probably installed twitter only for your default python version, in which case you should probably make a dedicated virtualenv pointing the good python executable version and installed using pip within the virtualenv

**Comment by RouxRC** [comment]
pip/ython versions look good but pip list doesn't seem to include twitter.
Maybe you only installed it for root, can you try to `pip install git+https://github.com/sixohsix/twitter.git` again without sudo?

**Comment by pikkupr** [comment]
It's in the list - twitter (1.17.1). I'll try it in a new conda environment, may b it is clashing with some other library!
Thanks for the help!

**Comment by dellsystem** [comment]
If you run `import twitter`, and then `help(twitter)`, what do you see?

**Comment by chrisdel101** [comment]
I have the same issue. Re-creating the env helped but I'm still getting the error. It's in my `pip3 list` and if I type `twitter` on the command line I get some twitter posts.
NameError: name 'Twitter' is not defined"
