### ISSUE TITLE
README mistake?

### ISSUE THREAD

**Issue by ghost** [sixohsix/twitter#351]
the code example in Working with OAuth section 

> twitter = Twitter(auth=OAuth(
>   oauth_token, oauth_token_secret, CONSUMER_KEY, CONSUMER_SECRET))

it should be:

twitter = Twitter(auth=OAuth(
    oauth_token, oauth_secret, CONSUMER_KEY, CONSUMER_SECRET))

**Comment by hugovk** [comment]
Thanks, see https://github.com/sixohsix/twitter/pull/367 for a fix.
