### ISSUE TITLE
Let someone else create releases

### ISSUE THREAD

**Issue by sixohsix** [sixohsix/twitter#356]
I am the only one capable of creating a release of this package and uploading it to PyPI, but I rarely use Python or this package any more, which means that I forget to cut new releases. Someone who has more interest in this project should get the upload keys.

@RouxRC You are the only other person with push access to this repo, and you've been faithfully maintaining this code while I've been negligent about it. Thank you very much, by the way! Would you like access to PyPI so that you can also cut releases? If so, please tell my your username there.

**Comment by tedder** [comment]
wow, it'd be great to get updates here. you don't know me from Adam but I'm `tedder` over there too. I'd love to at least take the baton in the short-term.

**Comment by RouxRC** [comment]
Hi Mike, thanks for the proposition. Although, I personally don't have a pypi account yet /o\
I'll happily do it, but might need a few hints on your usual process and version numbering beforehand.

**Comment by hugovk** [comment]
I recommend creating a release checklist in RELEASING.md as a handy reference guide at release time.

Some examples: 
* https://github.com/python-pillow/Pillow/blob/master/RELEASING.md
* https://github.com/pylast/pylast/blob/develop/RELEASING.md
* https://github.com/djc/couchdb-python/blob/master/RELEASING.rst
* https://github.com/nanomsg/nanomsg/blob/master/RELEASING

**Comment by kerstin** [comment]
Hmm... maybe create a Gitter channel where people interested in maintaining this repo could discuss stuff with you, @sixohsix?

**Comment by RouxRC** [comment]
Hey @sixohsix I'm resurrecting this thread as i realized we could definitely use a new release here. I now have a pypi account ("boogheta"), could you give me the rights for the twitter package?

**Comment by sixohsix** [comment]
@RouxRC I invited you to be an owner of the twitter package on PyPI. I am giving you full authority to take the twitter package and do whatever you want with it. You have maintained this package extremely well for a long time, and as for me... I'm not even really on Twitter any more.

If you want to move this repository to your own GitHub space so that your name is on it, I'm okay with that too. I don't know what facilities GitHub has for moving a repo along with its associated issues, but if it's possible, I will certainly give it to you. Otherwise, this repo will stay here for the foreseeable future.

You should also change the README that includes the example code that sends a message to `@sixohsix` and put your Twitter handle there. Then you can get the flood of notifications when an entire class of students tries out the library simultaneously. (It's fun, I promise.) 😄 

Anyway, like I said, you are maintaining this library very well. As far as I'm concerned, you own it already.

**Comment by sixohsix** [comment]
@hugovk I also wanted to praise you for the work you've done maintaining this library. I gave the PyPI keys to Benjamin because he asked first, but perhaps you both should have access. I trust you two to work out how you want to make releases going forward, and as part of that plan, share access however it makes sense to do so. You were a big part of keeping this library afloat while the Twitter API itself changed (and got weirder and weirder over time). Thank you so much.

If there's anything I can do for you, please let me know.

**Comment by keikoro** [comment]
Perhaps it might make sense to move the repo to its own organisation account? https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams

**Comment by hugovk** [comment]
@sixohsix You're very welcome! And thank you too for writing this in the first place, and of course also @RouxRC for maintaining!

I've been using this library for fun Twitter bots, but as Twitter has made things harder for developers, and suspended/re-suspended a bunch of my bots with no notice, I'm less and less incentivised to carry on when they break (or get suspended, as is usually the case).

But, I still have a few bots ticking over, and can help out with some basic maintenance, but probably not things like developing new features or fixing bugs as I'm maintaining quite a few projects already. Feel free to add me, even if just to reduce the bus factor.

Something that could be useful: I could help set up automated deploys to PyPI for tagged releases (using https://github.com/pypa/gh-action-pypi-publish). Releases are not so frequent here, but would that be useful?

**Comment by RouxRC** [comment]
Hello Mike and lots of thanks! Will try to be up to the task :)

Seeing how this lib keeps working without too much maintenance on the long run illustrates your initial choices for its low-level adaptative philosophy were the good ones, and I guess this is why I've liked it from the beginning and wanted to help. So thanks again to you for initiating this great lib!

I also want to thank Hugo for his help for the past years: you have way more experience than I do with packaging and CI and it has proved really useful and efficient. Therefore, I'll be happy to share pypi keys with you too, and yes, I'd love to have a streamlined pypi release process using tagged releases from github, that would be perfect! What's your pypi account? I can set you as owner or maintainer as you prefer depending on your potential needs, let me know!

I personnally don't see any reason to migrate the repo under my github account, but why not a dedicated organization indeed as suggested by @keykoro, but I also like the idea to keep it under @sixohsix as a legacy marker. What do you think Hugo ?.

Also I must admit I've not been maintaining at all the CLI part of the lib, which keeps getting quite some issues regularily, so maybe it might be time soon to release a v2 without it, refocusing the lib on its python library use, and adding some pointers to other options for CLI (twint, twarc, minet, snscrape, etc.) ?
(but I guess this shall be discussed in another issue)

PS: and yes, all right @sixohsix, I will take over the example with my Twitter handle right away and experience the flood come :)

**Comment by hugovk** [comment]
You're very welcome too :) I'm also `hugovk` on PyPI, either role is fine for me! I'll make a PR for automated deploys this week.

**Comment by RouxRC** [comment]
All right, I've just added you as maintainer, but I'll upgrade you to owner if it appears you require it.
Also, I feel like at least for your CI commits you could avoid going through the PR process (and push either on branches during tests, or directly on master when just removing a python version for the tests for instance), so I can give you also push rights on the repo if you'd like, let me know!
