### ISSUE TITLE
Support line breaks (\n) when setting status

### ISSUE THREAD

**Issue by skpy** [sixohsix/twitter#358]
Twitter permits line breaks, allowing one to somewhat format messages.  Trying to use `twitter set "this is a message\nthis is something else"` puts the literal `\n` in the status output.

It would be super swell if the `twitter` command could support new lines.

**Comment by hugovk** [comment]
Line breaks are supported when using this library as an API.

For example, these bots:
https://twitter.com/botknock
https://twitter.com/mydogsgotno

And their source:
https://github.com/hugovk/botknock/blob/master/botknock.py#L160-L164
https://github.com/hugovk/mydogsgotno/blob/master/mydogsgotno.py#L78

So sounds like a problem in the command-line tool.

**Comment by RouxRC** [comment]
I guess it only relies on adding """statusTxt = statusTxt.replace('\\n', '\n')""" line 577 here https://github.com/sixohsix/twitter/blob/master/twitter/cmdline.py#L577

@skpy can you try it and propose a pull request if that solves it?

**Comment by skpy** [comment]
Confirmed: that allowed me to insert line breaks into my tweets from the command line.

**Comment by hugovk** [comment]
PR: https://github.com/sixohsix/twitter/pull/359
