### ISSUE TITLE
Is there a way to get last x tweets or the tweets in the last hour?

### ISSUE THREAD

**Issue by hkyq** [sixohsix/twitter#360]
I'm aware of twitter-log, but I'm not really sure how to use the date command.

**Comment by RouxRC** [comment]
Hi,
What do you mean last tweets? from a specific user? for a specific searched keyword?

**Comment by hkyq** [comment]
Yes, from a specific user. I was gonna try to make a led blink everytime someone important tweets. I've got the leds configured. Thanks for responding so fast @RouxRC

**Comment by RouxRC** [comment]
It seems like for your need using the stream would be the best option as it would let you get new tweets live when they are posted. Although you will have to code a little bit, there's an example here https://github.com/sixohsix/twitter/blob/master/twitter/stream_example.py and API documentation there https://dev.twitter.com/streaming/reference/post/statuses/filter

**Comment by hkyq** [comment]
Thank you, I will check it out @RouxRC
