### ISSUE TITLE
API statuses/lookup

### ISSUE THREAD

**Issue by eriktks** [sixohsix/twitter#362]
When I call the API statuses/lookup, the id argument is appended to the url, which is not what I want. I hacked myself around this problem by commenting away lines 170-172 of twitter/api.py but probably there is a better solution.

results = t.statuses.lookup(id="12345")

error: Twitter sent status 404 for URL: 1.1/statuses/lookup/12345.json using parameters: ...
details: {u'errors': [{u'message': u'Sorry, that page does not exist', u'code': 34}]}

**Comment by boogheta** [comment]
Hi, I think what you need is to use here is the "_id" param as shown in this example here  https://github.com/sixohsix/twitter#the-twitter-class:
`results = t.statuses.lookup(_id="12345")`

**Comment by eriktks** [comment]
That's the solution I was looking for. Thanks!
