### ISSUE TITLE
Truncated tweets after API update

### ISSUE THREAD

**Issue by skjaeve** [sixohsix/twitter#369]
twitter-archiver returns truncated tweets after an API update. See https://developer.twitter.com/en/docs/tweets/tweet-updates and https://stackoverflow.com/a/40454382/912307 .

The following diff seems to fix it for twitter-archiver. I have no idea if it breaks anything else.

````
diff --git a/twitter/archiver.py b/twitter/archiver.py
index ef2dc1f..ae60380 100644
--- a/twitter/archiver.py
+++ b/twitter/archiver.py
@@ -190,7 +190,7 @@ def statuses_resolve_uids(twitter, tl):
 
 def statuses_portion(twitter, screen_name, max_id=None, mentions=False, favorites=False, received_dms=None, isoformat=False):
     """Get a portion of the statuses of a screen name."""
-    kwargs = dict(count=200, include_rts=1, screen_name=screen_name)
+    kwargs = dict(count=200, include_rts=1, screen_name=screen_name, tweet_mode='extended')
     if max_id:
         kwargs['max_id'] = max_id
 
@@ -217,10 +217,10 @@ def statuses_portion(twitter, screen_name, max_id=None, mentions=False, favorite
     else:
       newtl = tl
     for t in newtl:
-        text = t['text']
+        text = t['full_text']
         rt = t.get('retweeted_status')
         if rt:
-            text = "RT @%s: %s" % (rt['user']['screen_name'], rt['text'])
+            text = "RT @%s: %s" % (rt['user']['screen_name'], rt['full_text'])
         # DMs don't include mentions by default, so in order to show who
         # the recipient was, we synthesise a mention. If we're not
         # operating on DMs, behave as normal
````

**Comment by boogheta** [comment]
That's the way to go, can you propose it as a Pull Request? Thx

**Comment by hugovk** [comment]
Here's a PR: https://github.com/sixohsix/twitter/pull/371.

Any tips how to use 280 characters with streaming using `from twitter.stream import TwitterStream`?

**Comment by RouxRC** [comment]
@hugovk there's no extra option to add to stream api calls, but you need to collect new full text fields from the new "extended_tweet" field for each tweet. See for instance : https://github.com/medialab/gazouilloire/commit/f350380dbff71efaf9f7931eb181964e008b9f07#diff-a5580cc12ad805c63543d907a4931255

**Comment by hugovk** [comment]
Aha, there it is, thanks!
