### ISSUE TITLE
Package name is same as the another twitter package called "python-twitter"

### ISSUE THREAD

**Issue by jasonyanwenl** [sixohsix/twitter#379]
This is issue cannot be avoided if someone want to install both of them and make some comparison. For me, both this package and the `python-twitter` will be installed into the same directory named `twitter`.

**Comment by boogheta** [comment]
Well I guess the issue rather comes from the package that installs itself in a directory with a different name than its own no?
Whatsoever, you can install them separately in two virtualenvs for your test purposes
