### ISSUE TITLE
How to get a tweet object in json in order to track it's stats over it's lifetime...

### ISSUE THREAD

**Issue by TechTard88** [sixohsix/twitter#381]
How to get a tweet object in json in order to track it's stats over it's lifetime...

tweetObject = t.statuses.update(auth(OAuth("keys....")) Blah blah blah

Question: Is tweetObject an actual tweet object?

Because the json I get has a 'u' before each json parameter. I'm thinking that stands for user?... 
Anyways I simply want to post a tweet and get the id of that tweet in order to track things like, likes and retweets and such. BTW I'm a noob if you haven't noticed. Any help or advice is greatly appreciated. Thanks in advance.

**Comment by RouxRC** [comment]
Hi,
This is because what you're printing is a python2 object, with strings stored as unicode, hence the `u"unicode_string"` pattern. You can print it in json using `json.dumps` for instance.
