### ISSUE TITLE
Will Twitter API update affect this repo?

### ISSUE THREAD

**Issue by EnduringBeta** [sixohsix/twitter#382]
I use this repo for my Twitter bot, and I got an email from Twitter saying that they were updating their API with respect to direct messages, namely deprecating certain end points. Does this affect this repo?

https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html

**Comment by sixohsix** [comment]
Hi,

Your application may be affected, depending on what parts of the Twitter API you used. If you used the direct message endpoints, they will no longer work. As well, if you used the streaming API endpoints, those also will not work. (The streaming API documentation and example code should get removed from this repo at some point as it will no longer work.)

Everything else should work as before.

Some of the removed features have been replaced by "webhook" endpoints. Python Twitter Tools doesn't support webhook endpoints, and there is no plan to add support for them at this time.

That's the state of things right now.

**Comment by boogheta** [comment]
You can read the details on how to migrate from the old DM way to the new here: https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration

**Comment by EnduringBeta** [comment]
Thank you for this information. I assumed it would break my current implementation with this repo, but I appreciate the confirmation and the direction for how to update.

**Comment by ryonakamura** [comment]
@sixohsix 
Will all `TwitterStream()` become unusable?  
Or will `TwitterStream(domain='userstream.twitter.com')` only become unusable?  
If `domain='stream.twitter.com'` also becomes unusable, is there an alternative means?  
Sorry to ask questions with closed Issue.

**Comment by sixohsix** [comment]
All TwitterStream endpoints will become unusable on August 16, 2018.

This is an excerpt from the announcement:

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html

> As a few developers have noticed, there’s no streaming connection capability or home timeline data, which are only used by a small amount of developers (roughly 1% of monthly active apps). As we retire aging APIs, we have no plans to add these capabilities to Account Activity API or create a new streaming service for related use cases.

So, no, that's it. Twitter doesn't care.

**Comment by ryonakamura** [comment]
Thank you. I understand. 😭😭😭

**Comment by RouxRC** [comment]
Well actually, let me respectfully disagree :)
Not all TwitterStream will become ususable : they only list explicitly sitestream.twitter.com and userstream.twitter.com, but not stream.twitter.com which is the one used for the "statuses/filter" that allows live tracking of searched keywords and users.
For what I understand, they only discontinue stream used for timelines, and I don't think they will remove the search one (maybe limit it more though) since it's their best entry advertisement point for their paying PowerTrack and Replay APIs https://developer.twitter.com/en/docs/tweets/filter-realtime/overview/statuses-filter

**Comment by sixohsix** [comment]
Oh? Hmm, I didn't know that. Thanks for trying me!

So I guess we shouldn't delete the streaming code. Might have to audit the readme, though.

**Comment by RouxRC** [comment]
sounds fair :)
