### ISSUE TITLE
stream_example.py obsolete?

### ISSUE THREAD

**Issue by kerstin** [sixohsix/twitter#384]
Am I correct in that this file is obsolete now that the old Streaming APIs have been turned off? It definitely gives an error:

`The Site Streams and User Streams endpoints have been turned off. Please migrate to alternate APIs. See https://t.co/usss`

I was trying to get sample statuses but it reads to me like these are only available to paying customers (Decahose) now? https://developer.twitter.com/en/docs/tweets/sample-realtime/overview/GET_statuse_sample

(I'll add I still don't fully understand Twitter's new products.)

**Comment by RouxRC** [comment]
https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter
https://developer.twitter.com/en/docs/tweets/sample-realtime/api-reference/get-statuses-sample

**Comment by RouxRC** [comment]
Indeed the calls to userstream and sitestream are now deprecated, I removed them. For the reste my understanding is that streams on the regular domain stream.twitter.com remain :
- filter realtime : https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter
- sample realtime : https://developer.twitter.com/en/docs/tweets/sample-realtime/api-reference/get-statuses-sample

The lib might work as well with the other paying streams of PowerTrack and Decahose APIs but i've never got the privilege to use it so I haven't investigated it nor wouldn't know.
