### ISSUE TITLE
Outdated links to API documentation in README

### ISSUE THREAD

**Issue by kerstin** [sixohsix/twitter#385]
One section in the `README` reads:

> The Twitter API is documented at:
> 
> https://dev.twitter.com/overview/documentation
> 
> The list of most accessible functions is listed at:
> 
> https://dev.twitter.com/rest/public

These links now all redirect to https://developer.twitter.com/en/docs - the API documentation is fragmented now and that list of functions doesn't exist anymore as such.

I'm guessing a rewrite should make clear(er) which of Twitter's API(s) the project is currently applicable to.

**Comment by RouxRC** [comment]
There is still a list here: https://developer.twitter.com/en/docs/api-reference-index
Thx for the notice, I've updated the README

**Comment by kerstin** [comment]
Ohh, I've looked at/over different parts of the API docs several times within the last 2 weeks but never found that list. o__O Thanks!
