### ISSUE TITLE
how to start, i am newbie ! I did: pip install twitter, How to open the program ?

### ISSUE THREAD

**Issue by hddeus** [sixohsix/twitter#390]

**Comment by hddeus** [comment]
@clarkbw @muitocomplicado @davecap @kennu

**Comment by hddeus** [comment]
@RouxRC @endlisnis

**Comment by hddeus** [comment]
@sixohsix @dragonfax

**Comment by hddeus** [comment]
I would like to know : 
1- How can i start the program?

**Comment by hugovk** [comment]
This is not a program or app, it's a library for developers to use when writing their own programs that want to do things with Twitter.

**Comment by hddeus** [comment]
Could you give me a example of something written ?

Could you post a text example ?

**Comment by brayo-pip** [comment]
okay after pip install twitter

>twitter -h
/* u will get redirected to a webbrowser copy n paste the pip*/

>twitter
// your recent tweets displayed
