### ISSUE TITLE
Does retry wait until API limit window is reset?

### ISSUE THREAD

**Issue by robroc** [sixohsix/twitter#391]
The `retry` parameter when initiating `twitter.Twitter` is great, but I'd like to understand it better. Does it just keep trying every few seconds until there are no more error codes, or does it check the API window reset and then tries again?

**Comment by robroc** [comment]
I just did a quick test, it still works with the API, even if the error headers are in lowercase: `x-rate-limit-reset`.  Good to know!

**Comment by RouxRC** [comment]
HTTP Headers keys are supposed to be case-insensitive so that's all right yes!
I'm closing this, feel free to reopen if a question remains :)
