### ISSUE TITLE
Response Object

### ISSUE THREAD

**Issue by mygithubaccount12** [sixohsix/twitter#392]
Hello, 
I'm greatful for this library.  I think it's pretty neat.

I'm really stuck on the 'Response' section.  For almost 5 hours I've been trying to get into the headers to see where I am in terms of rate usage and I am completely stumped.

Here's the documentation which is surprisingly sparse (or probably better stated, it makes more sense to people who really know what they are doing):

 `headers` gives you access to the response headers as an `httplib.HTTPHeaders` instance. Use `response.headers.get('h')` to retrieve a header.

There's no example, and I tried almost everything I could think of to get it to work.

Can someone help me by posting an example?

A suggestion I would have is to have it easily accessable, and maybe it is but I just can't get to it.

I've tried at least the following code to get it to work:

Tried this:
```
t = twitter_authentication()
t.statuses.home_timeline(count=1)
pprint(t.response.headers.get('h'))
```
Error = "TypeError: __call__() takes 1 positional argument but 2 were given"

Tried this:
```
t = twitter_authentication()
t.statuses.home_timeline(count=1)
pprint(t.response.get('h'))
```
Error = TypeError: __call__() takes 1 positional argument but 2 were given

Tried this:
```
t = twitter_authentication()
t.statuses.home_timeline(count=1)
pprint(t.response('h'))
```
Error = TypeError: __call__() takes 1 positional argument but 2 were given

Tried this:
```
headers,response = t.statuses.home_timeline(count=1)
pprint(headers, response)
```
Error = ValueError: not enough values to unpack (expected 2, got 1)

Tried this:
```
t = twitter_authentication()
headers,response = t.response.headers.get('h'), t.statuses.home_timeline(count=1)
pprint(headers, response)
```
Error = TypeError: __call__() takes 1 positional argument but 2 were given

Tried this:
```
t = twitter_authentication()
x = t.statuses.home_timeline(response.headers.get('h'))
pprint(x)
```
Error = NameError: name 'response' is not defined

Tried this:
from twitter import response
```
t = twitter_authentication()
x = t.statuses.home_timeline(response.headers.get('h'))
pprint(x)
```
Error = ImportError: cannot import name 'response'

Tried this, and this is my only response that was not a result in an actual error:
```
t = twitter_authentication()
x = t.statuses.home_timeline(count=1)
pprint(x.headers.get('h'))
```
(Non-)Error = None

**Comment by RouxRC** [comment]
The last one is the way you should go with : the response object is the result of the call, so the headers attribute is attached to x.
The None result is just because there is not header "h". Just pprint(x.headers) to see them all and adapt h into the one you want.
