### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by ghost** [sixohsix/twitter#395]
Because some Twitter APIs are used without Twitter user authentication, such as GET statuses/home_timeline, but to use your installation package, you have to be an authenticated user. I feel limited.

**Comment by boogheta** [comment]
I don't understand your request, I don't know of any Twitter API route that would require any kind of authentication, the one you're pointing does as it says in the official documentation: https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-home_timeline
