### ISSUE TITLE
collections entries add fails with method requires POST

### ISSUE THREAD

**Issue by revelutions** [sixohsix/twitter#396]
I am trying to add an entry to a collection

> twitter_api.collections.entries.add(tweet_id='113934951708026****', _id='custom-11431331023628*****')

I get:

>   File "*****AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 400: Bad Request
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "***\AppData\Local\Programs\Python\Python36\lib\site-packages\twitter\api.py", line 334, in __call__
>     return self._handle_response(req, uri, arg_data, _timeout)
>   File "****\AppData\Local\Programs\Python\Python36\lib\site-packages\twitter\api.py", line 367, in _handle_response
>     raise TwitterHTTPError(e, uri, self.format, arg_data)
> twitter.api.TwitterHTTPError: Twitter sent status 400 for URL: 1.1/collections/entries/add.json using parameters: (id=custom-1143133102362877952&oauth_consumer_key=****&oauth_nonce=****&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1561886531&oauth_token=30438056****&oauth_version=1.0&tweet_id=****&oauth_signature=****%3D)
> details: {'errors': [{'code': 86, 'message': 'This method requires a POST.'}]}

---

Here is the API reference:
https://developer.twitter.com/en/docs/tweets/curate-a-collection/api-reference/post-collections-entries-add

I am able to call this using Postman

**Comment by RouxRC** [comment]
Hello, looking at the result error you get, I guess the lib sends à GET message. I believe this is a new API route and the list of methods requiring POST instead of GET is hardcoded in the lib, so it would deserve to be added there : 
In the mean time you can force using POST by adding the `_method="POST"` argument to your call.
