### ISSUE TITLE
pull request failed due to travis-ci nightly build fail with nosetest incompatible with python3.9-dev

### ISSUE THREAD

**Issue by ja70d** [sixohsix/twitter#405]
#404 failed to merge due to travis-ci nightly build failed
the build failed because of nosetest try to use collections.Callable in suit.py which [python3.9-dev (3.9.0a2) marks as REMOVED](https://docs.python.org/3.9/whatsnew/3.9.html)

**Comment by hugovk** [comment]
> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

https://nose.readthedocs.io/en/latest/

> nose2 may or may not be a good fit for your project.
>
> If you are new to python testing, we encourage you to also consider pytest, a popular testing framework.

https://docs.nose2.io/en/latest/

I also recommend pytest.

**Comment by hugovk** [comment]
Please see PR #406.

**Comment by ja70d** [comment]
@hugovk nice work!
