### ISSUE TITLE
NameError: name 'Twitter' is not defined

### ISSUE THREAD

**Issue by aadyarawat** [sixohsix/twitter#411]
I am trying to crete twitter authentication object in python and getting the error 
NameError: name 'Twitter' is not defined
It was working fine before but is not working now. The package installed is twitter and not 
python-twitter.

Please suggest a solution .

**Comment by boogheta** [comment]
Can you share some code and details on your install environment (are you using a virtualenv? what does `pip list` say?)

**Comment by aadyarawat** [comment]
No , Its not a virtual environment . 
pip list shows twitter 1.18 version

Code : from twitter import *
twitter = Twitter(auth = OAuth(consumer_key='',
                    consumer_secret='',
                    token='',
                    token_secret=''))

results = twitter.trends.place(_id = 23424975)

The keys are from my development app fetched from twitter account

Thank you for your reply!

**Comment by boogheta** [comment]
that is weird
Maybe try to avoid * and use instead `from twitter import Twitter, OAuth`

**Comment by hugovk** [comment]
Please can you share the full error traceback?

Do you have a file called twitter.py in your directory?

The following work for me:

```pycon
Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from twitter import *
>>> twitter = Twitter()
>>>
```
```pycon
Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from twitter import Twitter
>>> twitter = Twitter()
>>>
```

**Comment by boogheta** [comment]
Ha that's quite possible, good idea @hugovk !

**Comment by aadyarawat** [comment]
tried the same , not working

**Comment by boogheta** [comment]
Did you check whether there's a twitter.py file in your working directory? If so that's the problem

**Comment by aadyarawat** [comment]
Damn it worked!!
Thank you @hugovk @boogheta
